### PR TITLE
Add support for Llama2, Palm, Cohere, Anthropic, Replicate, Azure Models - using litellm 

### PR DESCRIPTION
**Pull request by ishaan-jaff**
Addressing this comment in the code, liteLLM adds support for 50+ models with a standard I/O interface: https://github.com/BerriAI/litellm/

> LangChain did not bother to standardize the names of any of the parameters,
> or even how to interact with them.  This is a hack to make things consistent.
    
`ChatLiteLLM()` is integrated into langchain and allows you to call all models using the OpenAI I/O interface 
https://python.langchain.com/docs/integrations/chat/litellm

Here's an example of how to use ChatLiteLLM()
```python
ChatLiteLLM(model="gpt-3.5-turbo")
ChatLiteLLM(model="claude-2", temperature=0.3)
ChatLiteLLM(model="command-nightly")
ChatLiteLLM(model="replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1")

```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@the-crypt-keeper can you please take a look at this PR ?😊

Happy to add docs/tests if this initial commit looks good

**Comment by the-crypt-keeper** [comment]
@ishaan-jaff Thanks for the PR! I was planning to look into this project exactly to see if it could clean things up, looks like you've already done the work here.  I've spawned #71 to track improving the documentation to both our global and interviewer-specific dependencies.

**Comment by ishaan-jaff** [comment]
Will keep an eye on this repo incase any issues arise

**Comment by ishaan-jaff** [comment]
@the-crypt-keeper wanted to check in - has LiteLLM ben working well for you? 

any features we can add for you ?

**Comment by ishaan-jaff** [comment]
noticed you had a backlog of LLMs here: https://github.com/the-crypt-keeper/can-ai-code/issues 

happy to add the ones you think would be valuable to LiteLLM

**Comment by the-crypt-keeper** [comment]
@ishaan-jaff Appreciate the offer but I'm mainly focused on self-hosted LLMs for this project, the few commercial models I test are mostly for sanity.

**Comment by krrishdholakia** [comment]
@the-crypt-keeper how do you deploy those?

**Comment by the-crypt-keeper** [comment]
@krrishdholakia [interview_cuda.py](https://github.com/the-crypt-keeper/can-ai-code/blob/main/interview_cuda.py) wraps a growing number of inference engines and has a CLI, but as my local GPU is only 12GB I generally rely on the [interview_modal.py](https://github.com/the-crypt-keeper/can-ai-code/blob/main/interview_modal.py) wrapper that lets me rent GPUs by the second.

**Pull request merged**
