### PR TITLE
WIP: Upgrade all dependencies to support CodeLlama

### PR DESCRIPTION
**Pull request by the-crypt-keeper**
vLLM is still returning gibberish on both TheBloke and codellama versions of the fp16

### CODE REVIEW

**Comment by the-crypt-keeper** [comment]
https://github.com/vllm-project/vllm/issues/883

**Comment by the-crypt-keeper** [comment]
https://github.com/vllm-project/vllm/issues/900 suggests to use official codellama models but the .bin not the .safetensors, worth a shot. also going to pull transformers up to 4.33 now that it's officially released

**Comment by viktor-ferenczi** [comment]
Official CodeLlama at 16 bits is too large to load for most people. GGUF support would be really useful and welcome here.

**Comment by the-crypt-keeper** [comment]
Merged manually.

**Pull request closed without merging**
